# Title of your site
title = "STA 210"

# The URL of your site.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = "https://www.tidymodels.org/"

# Name the theme folder in `themes/`.
theme = "hugo-tourmaline"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = ""

relativeurls = false
languageCode = "en-us"
description = "Website for STA 210: Regression Analysis at Duke University"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
# below is critical for non-authors to show up in article listing
preserveTaxonomyNames = true
# uncomment the next line to disable listing authors
# disableKinds = ["taxonomyTerm"]

[permalinks]
  articles = "news/:year/:month/:slug/"

[taxonomies]
  author = "author"
  category = "categories"
  tag = "tags"

# Configure BlackFriday Markdown rendering.
#   See: https://gohugo.io/getting-started/configuration/#configure-blackfriday
[blackfriday]
  hrefTargetBlank = true  # `true` opens external links in a new tab. See https://github.com/gohugoio/hugo/issues/2424
	angledQuotes = false
	latexDashes = true
  extensions = ["backslashLineBreak"]

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.tableOfContents]
    endLevel = 2
    ordered = false
    startLevel = 2
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    style = "pygments"
